// ─────────────────────────────────────────────────────────────────────────────
// Palette — generated ramps, not hand-picked hexes.
//
// The scenery used to mix three published design systems (two different Coolors
// sets and a handful of Tailwind and Material defaults) across 146 literal hex
// values. Colours picked one at a time don't sit together no matter how nice
// each one is on its own, because what makes art read as lit form is the
// *relationship* between a colour and its own shadow.
//
// So the ramps here are generated by one rule, the rule every pixel artist
// uses: as a colour darkens it rotates toward the ambient sky hue, and as it
// lightens it rotates toward the light source. A ramp that only changes
// lightness reads as a flat tint with the brightness turned down; a ramp that
// shifts hue reads as a surface turning away from the sun.
//
// These are ours rather than a Lospec import: swapping in a published ramp
// later means replacing the constants at the bottom of this file and nothing
// else, but a ramp copied from memory is a ramp nobody has verified.
// ─────────────────────────────────────────────────────────────────────────────

/** Hue the shadows rotate toward — the ambient bounce from an open sky. */
const SHADOW_HUE = 232;
/** Hue the highlights rotate toward — direct sun. */
const LIGHT_HUE = 44;

function clamp01(n: number) {
  return Math.min(1, Math.max(0, n));
}

/** Shortest-path interpolation around the colour wheel. */
function hueLerp(from: number, to: number, t: number): number {
  const delta = ((((to - from) % 360) + 540) % 360) - 180;
  return (((from + delta * t) % 360) + 360) % 360;
}

function toHex(n: number) {
  return Math.round(clamp01(n) * 255)
    .toString(16)
    .padStart(2, "0");
}

export function hslToHex(h: number, s: number, l: number): string {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const seg = Math.floor(h / 60) % 6;
  const [r, g, b] = [
    [c, x, 0],
    [x, c, 0],
    [0, c, x],
    [0, x, c],
    [x, 0, c],
    [c, 0, x],
  ][seg];
  return `#${toHex(r + m)}${toHex(g + m)}${toHex(b + m)}`;
}

interface RampSpec {
  /** Base hue in degrees. */
  hue: number;
  /** Saturation at the middle of the ramp, 0–1. Both ends fall off from here. */
  sat: number;
  /** Lightness at the darkest step, 0–1. */
  dark: number;
  /** Lightness at the lightest step, 0–1. */
  light: number;
  /** How far the dark end rotates toward SHADOW_HUE, 0–1. */
  shadowPull?: number;
  /** How far the light end rotates toward LIGHT_HUE, 0–1. */
  lightPull?: number;
}

/**
 * `steps` colours, darkest first.
 *
 * Saturation peaks in the midtones and falls off at both ends: the darkest
 * step is close to the ambient shadow and the lightest is close to the light
 * source, and neither is a saturated version of the base colour. Skipping this
 * is what makes a ramp look like a slider was dragged.
 */
export function ramp(steps: number, spec: RampSpec): string[] {
  const { hue, sat, dark, light, shadowPull = 0.3, lightPull = 0.22 } = spec;
  return Array.from({ length: steps }, (_, i) => {
    const t = steps === 1 ? 0.5 : i / (steps - 1);
    const shifted = hueLerp(
      hueLerp(hue, SHADOW_HUE, shadowPull * (1 - t)),
      LIGHT_HUE,
      lightPull * t,
    );
    // Parabola through (0, .55·sat) → (.5, sat) → (1, .5·sat)
    const falloff = 1 - Math.pow((t - 0.5) * 2, 2);
    const s = sat * (0.52 + 0.48 * falloff);
    return hslToHex(shifted, clamp01(s), dark + (light - dark) * t);
  });
}

// ── Colour maths used for depth ─────────────────────────────────────────────

function parseHex(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}

/** Mix two hexes; `t` 0 = `a`, 1 = `b`. */
export function blend(a: string, b: string, t: number): string {
  const [ar, ag, ab] = parseHex(a);
  const [br, bg, bb] = parseHex(b);
  const k = clamp01(t);
  return `#${toHex((ar + (br - ar) * k) / 255)}${toHex((ag + (bg - ag) * k) / 255)}${toHex((ab + (bb - ab) * k) / 255)}`;
}

/**
 * How much of the sky sits between the viewer and a layer.
 *
 * Depth in a flat scene has to come from *value*, not from size — a distant
 * ridge is not a small near ridge, it is a low-contrast one. Air scatters
 * light, so everything far away converges on the colour of the sky, loses
 * contrast, and loses saturation. Get this right and a scene reads as deep
 * with no perspective at all; leave it out and every layer sits on the glass.
 */
export const HAZE = {
  far: 0.62,
  mid: 0.34,
  near: 0.14,
  front: 0,
} as const;

export type Depth = keyof typeof HAZE;

/** Push one colour toward the sky by a depth's worth of air. */
export function hazed(color: string, sky: string, depth: Depth): string {
  return blend(color, sky, HAZE[depth]);
}

/** Push a whole sprite palette back by the same amount. */
export function hazedPalette<T extends Record<string, string>>(
  palette: T,
  sky: string,
  depth: Depth,
): T {
  if (HAZE[depth] === 0) return palette;
  const out = {} as Record<string, string>;
  for (const [key, value] of Object.entries(palette)) {
    out[key] = hazed(value, sky, depth);
  }
  return out as T;
}

// ── The ramps ───────────────────────────────────────────────────────────────
// Darkest first. Index them; don't copy the values out.

/** Conifer and canopy greens. */
export const FOLIAGE = ramp(6, { hue: 148, sat: 0.42, dark: 0.14, light: 0.7 });
/** Grass and undergrowth — yellower and lighter than FOLIAGE so they separate. */
export const GRASS = ramp(5, { hue: 108, sat: 0.38, dark: 0.2, light: 0.72 });
/** Trunks, branches, timber. */
export const BARK = ramp(5, { hue: 26, sat: 0.4, dark: 0.13, light: 0.56 });
/** Rock, cliff, road, anything mineral. */
export const STONE = ramp(6, { hue: 224, sat: 0.13, dark: 0.16, light: 0.72 });
/** Snow and cloud — barely saturated, but not grey. */
export const SNOW = ramp(4, { hue: 214, sat: 0.14, dark: 0.62, light: 0.98 });
/**
 * Lit windows, lamps, embers.
 *
 * Barely any shadowPull: a light source has no shadowed side to rotate toward
 * the sky, and pulling a warm hue toward blue takes the short way round through
 * red — which turned the dark end of this ramp pink the first time.
 */
export const EMBER = ramp(4, {
  hue: 40,
  sat: 0.78,
  dark: 0.38,
  light: 0.88,
  shadowPull: 0.04,
  lightPull: 0.06,
});
