// ─────────────────────────────────────────────────────────────────────────────
// Palette — generated ramps, not hand-picked hexes.
//
// The scenery used to mix three published design systems (two different Coolors
// sets and a handful of Tailwind and Material defaults) across 146 literal hex
// values. Colours picked one at a time don't sit together no matter how nice
// each one is on its own, because what makes art read as lit form is the
// *relationship* between a colour and its own shadow.
//
// So the ramps here are generated by one rule, the rule every pixel artist
// uses: as a colour darkens it rotates toward the ambient sky hue, and as it
// lightens it rotates toward the light source. A ramp that only changes
// lightness reads as a flat tint with the brightness turned down; a ramp that
// shifts hue reads as a surface turning away from the sun.
//
// These are ours rather than a Lospec import: swapping in a published ramp
// later means replacing the constants at the bottom of this file and nothing
// else, but a ramp copied from memory is a ramp nobody has verified.
// ─────────────────────────────────────────────────────────────────────────────

/** Hue the shadows rotate toward — the ambient bounce from an open sky. */
const SHADOW_HUE = 232;
/** Hue the highlights rotate toward — direct sun. */
const LIGHT_HUE = 44;

function clamp01(n: number) {
  return Math.min(1, Math.max(0, n));
}

/** Shortest-path interpolation around the colour wheel. */
function hueLerp(from: number, to: number, t: number): number {
  const delta = ((((to - from) % 360) + 540) % 360) - 180;
  return (((from + delta * t) % 360) + 360) % 360;
}

function toHex(n: number) {
  return Math.round(clamp01(n) * 255)
    .toString(16)
    .padStart(2, "0");
}

export function hslToHex(h: number, s: number, l: number): string {
  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  const seg = Math.floor(h / 60) % 6;
  const [r, g, b] = [
    [c, x, 0],
    [x, c, 0],
    [0, c, x],
    [0, x, c],
    [x, 0, c],
    [c, 0, x],
  ][seg];
  return `#${toHex(r + m)}${toHex(g + m)}${toHex(b + m)}`;
}

interface RampSpec {
  /** Base hue in degrees. */
  hue: number;
  /** Saturation at the middle of the ramp, 0–1. Both ends fall off from here. */
  sat: number;
  /** Lightness at the darkest step, 0–1. */
  dark: number;
  /** Lightness at the lightest step, 0–1. */
  light: number;
  /** How far the dark end rotates toward SHADOW_HUE, 0–1. */
  shadowPull?: number;
  /** How far the light end rotates toward LIGHT_HUE, 0–1. */
  lightPull?: number;
}

/**
 * `steps` colours, darkest first.
 *
 * Saturation peaks in the midtones and falls off at both ends: the darkest
 * step is close to the ambient shadow and the lightest is close to the light
 * source, and neither is a saturated version of the base colour. Skipping this
 * is what makes a ramp look like a slider was dragged.
 */
export function ramp(steps: number, spec: RampSpec): string[] {
  const { hue, sat, dark, light, shadowPull = 0.3, lightPull = 0.22 } = spec;
  return Array.from({ length: steps }, (_, i) => {
    const t = steps === 1 ? 0.5 : i / (steps - 1);
    const shifted = hueLerp(
      hueLerp(hue, SHADOW_HUE, shadowPull * (1 - t)),
      LIGHT_HUE,
      lightPull * t,
    );
    // Parabola through (0, .55·sat) → (.5, sat) → (1, .5·sat)
    const falloff = 1 - Math.pow((t - 0.5) * 2, 2);
    const s = sat * (0.52 + 0.48 * falloff);
    return hslToHex(shifted, clamp01(s), dark + (light - dark) * t);
  });
}

// ── Colour maths used for depth ─────────────────────────────────────────────

function parseHex(hex: string): [number, number, number] {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 0xff, (n >> 8) & 0xff, n & 0xff];
}

/** Inverse of hslToHex. Hue in degrees, s and l in 0–1. */
export function hexToHsl(hex: string): [number, number, number] {
  const [r255, g255, b255] = parseHex(hex);
  const [r, g, b] = [r255 / 255, g255 / 255, b255 / 255];
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  const d = max - min;
  if (d === 0) return [0, 0, l];
  const s = d / (1 - Math.abs(2 * l - 1));
  let h: number;
  if (max === r) h = ((g - b) / d) % 6;
  else if (max === g) h = (b - r) / d + 2;
  else h = (r - g) / d + 4;
  return [((h * 60) % 360 + 360) % 360, s, l];
}

/**
 * The shaded side of a surface.
 *
 * Replaces a naive RGB multiply. Scaling channels by a ratio moves a *dark*
 * colour almost not at all — `darken('#4A2518', 0.08)` shifted value by about
 * 6/255, so the two deepest skin tones had a chin shadow nobody could see,
 * while the same call on the palest skin was obvious. Subtracting lightness
 * instead moves every colour by the same visible amount, and rotating toward
 * the ambient shadow hue is what makes it read as a surface turning away from
 * the light rather than as the same colour dimmed.
 *
 * Two things have to hold at once, and the obvious implementations each get
 * one of them:
 *
 * - **Every colour must darken by a visible amount.** Blending toward a fixed
 *   dark tone fails here, because a colour that is already dark barely moves —
 *   black hair came out 0.006 *lighter* than its own shadow.
 * - **Pale colours must not turn vivid.** Holding HSL `s` and dropping `l`
 *   fails here: `s` means different things at different lightnesses, so a
 *   peachy skin at l=0.85 shaded to l=0.75 came out pink.
 *
 * So: drop lightness by a fixed amount, and hold *chroma* rather than
 * saturation while doing it — chroma is `(1 - |2l - 1|) · s`, so `s` has to be
 * recomputed for the new lightness. Then rotate slightly toward the ambient
 * shadow hue, which is what makes it read as a surface turning away from the
 * light instead of the same colour dimmed.
 *
 * `drop` is in lightness units, not a ratio.
 */
export function shade(hex: string, drop = 0.1): string {
  const [h, s, l] = hexToHsl(hex);
  const lit = Math.max(0.04, l - drop);
  const chroma = (1 - Math.abs(2 * l - 1)) * s;
  const spread = 1 - Math.abs(2 * lit - 1);
  // Chroma preservation asks for more and more saturation as lightness falls,
  // and near the bottom it asks for impossible amounts — the deepest skin came
  // back as a saturated near-black red. Cap the rise: hold chroma where that
  // is achievable, and give up on it rather than produce a colour harsher than
  // the one it is shading.
  const sat = Math.min(s * 1.12, spread === 0 ? 0 : chroma / spread);
  // Warm hues take the short way round to the ambient blue, i.e. through red —
  // the same trap that turned the EMBER ramp pink. That is the right direction
  // for skin and hair anyway (warm shadows go red-violet, not blue), so the
  // pull stays small and the path is left alone.
  return hslToHex(hueLerp(h, SHADOW_HUE, 0.1), clamp01(sat), lit);
}

/**
 * Cheeks, on any skin.
 *
 * Was a fixed `#F4A0A0` at 0.6 opacity, which on the palest skin is a blush
 * and on `#4A2518` is two bright pink stripes — the mark was being painted
 * *over* the face instead of being the face flushing. Deriving it from the
 * skin keeps the value where it was and moves only hue and saturation, so it
 * reads as warmth at every tone. Opacity is gone with it: a flat colour is one
 * fewer thing between the sprite and `crispEdges`.
 */
export function flush(skin: string): string {
  const [h, s, l] = hexToHsl(skin);
  return hslToHex(
    hueLerp(h, 8, 0.4),
    clamp01(s * 1.18 + 0.06),
    // Warmth reads as a lift on deep skin and a deepening on pale skin, which
    // is also how blood under skin actually behaves.
    clamp01(l < 0.45 ? l + 0.05 : l - 0.04),
  );
}

/** Mix two hexes; `t` 0 = `a`, 1 = `b`. */
export function blend(a: string, b: string, t: number): string {
  const [ar, ag, ab] = parseHex(a);
  const [br, bg, bb] = parseHex(b);
  const k = clamp01(t);
  return `#${toHex((ar + (br - ar) * k) / 255)}${toHex((ag + (bg - ag) * k) / 255)}${toHex((ab + (bb - ab) * k) / 255)}`;
}

/**
 * An outline that stays visible against whatever it is drawn on.
 *
 * The scenery's keyline is always dark, which is right on a daylit world and
 * useless on a dark one: the Space world's air is `#04001A`, so a dark-haired
 * avatar and a dark outline dissolve into it together and the outline buys
 * nothing at the exact moment the silhouette needs help. Choosing on the
 * backdrop's lightness is what makes one rule work for all eight worlds.
 *
 * Softened toward the backdrop rather than run at full contrast: a pure keyline
 * on a 3px art pixel reads as a thick black marker line around a small figure.
 */
const KEYLINE_DARK = "#1b1b1b";
const KEYLINE_LIGHT = "#e8e4dc";
const KEYLINE_SOFTEN = 0.25;

export function keylineOn(backdrop: string): string {
  const [, , l] = hexToHsl(backdrop);
  return blend(l < 0.5 ? KEYLINE_LIGHT : KEYLINE_DARK, backdrop, KEYLINE_SOFTEN);
}

/**
 * How much of the sky sits between the viewer and a layer.
 *
 * Depth in a flat scene has to come from *value*, not from size — a distant
 * ridge is not a small near ridge, it is a low-contrast one. Air scatters
 * light, so everything far away converges on the colour of the sky, loses
 * contrast, and loses saturation. Get this right and a scene reads as deep
 * with no perspective at all; leave it out and every layer sits on the glass.
 */
export const HAZE = {
  far: 0.62,
  mid: 0.34,
  near: 0.14,
  front: 0,
} as const;

export type Depth = keyof typeof HAZE;

/** Push one colour toward the sky by a depth's worth of air. */
export function hazed(color: string, sky: string, depth: Depth): string {
  return blend(color, sky, HAZE[depth]);
}

/** Push a whole sprite palette back by the same amount. */
export function hazedPalette<T extends Record<string, string>>(
  palette: T,
  sky: string,
  depth: Depth,
): T {
  if (HAZE[depth] === 0) return palette;
  const out = {} as Record<string, string>;
  for (const [key, value] of Object.entries(palette)) {
    out[key] = hazed(value, sky, depth);
  }
  return out as T;
}

// ── The ramps ───────────────────────────────────────────────────────────────
// Darkest first. Index them; don't copy the values out.

/** Conifer and canopy greens. */
export const FOLIAGE = ramp(6, { hue: 148, sat: 0.42, dark: 0.14, light: 0.7 });
/** Grass and undergrowth — yellower and lighter than FOLIAGE so they separate. */
export const GRASS = ramp(5, { hue: 108, sat: 0.38, dark: 0.2, light: 0.72 });
/** Trunks, branches, timber. */
export const BARK = ramp(5, { hue: 26, sat: 0.4, dark: 0.13, light: 0.56 });
/** Dry sand and dune. */
export const SAND = ramp(5, {
  hue: 44,
  sat: 0.34,
  dark: 0.34,
  light: 0.86,
  shadowPull: 0.18,
});
/** Rock, cliff, road, anything mineral. */
export const STONE = ramp(6, { hue: 224, sat: 0.13, dark: 0.16, light: 0.72 });
/** Snow and cloud — barely saturated, but not grey. */
export const SNOW = ramp(4, { hue: 214, sat: 0.14, dark: 0.62, light: 0.98 });
/**
 * Lit windows, lamps, embers.
 *
 * Barely any shadowPull: a light source has no shadowed side to rotate toward
 * the sky, and pulling a warm hue toward blue takes the short way round through
 * red — which turned the dark end of this ramp pink the first time.
 */
export const EMBER = ramp(4, {
  hue: 40,
  sat: 0.78,
  dark: 0.38,
  light: 0.88,
  shadowPull: 0.04,
  lightPull: 0.06,
});
