import { randomUUID } from 'node:crypto';
import { test, expect, AUTH_STORAGE_KEY } from './duoFixture';
import { onboard } from './onboard';

test('each person names their companion, keeps names through switching and reconnect, and restores defaults', async ({ duo }) => {
  test.setTimeout(120_000);
  const { a, b, roomCodes } = duo;
  const suffix = randomUUID().slice(0, 8);
  const errors: string[] = [];
  for (const actor of [a, b]) actor.page.on('pageerror', () => errors.push('browser error'));
  async function unlock(page: typeof a.page) {
    await page.getByRole('button', { name: 'Cat (unlock companions)' }).click();
    const dialog = page.getByRole('dialog', { name: 'Companions', exact: true });
    await dialog.getByRole('button', { name: 'Unlock companions', exact: true }).click();
    await dialog.getByRole('button', { name: 'Done', exact: true }).click();
  }
  await a.page.goto('/');
  await onboard(a.page, 'Names Alpha', `na_${suffix}`);
  await a.page.getByRole('button', { name: 'Focus', exact: true }).click();
  await expect(a.page.getByRole('button', { name: 'Start solo', exact: true })).toBeVisible();
  await unlock(a.page);
  await a.page.getByRole('button', { name: 'Cat', exact: true }).click();
  const editor = (page: typeof a.page) => page.getByRole('region', { name: 'Your companion name' });
  await expect(editor(a.page).getByText('Mochi', { exact: true })).toBeVisible();
  async function rename(page: typeof a.page, name: string) {
    await editor(page).getByRole('button', { name: 'Rename companion' }).click();
    await editor(page).getByRole('textbox', { name: 'Companion name' }).fill(name);
    await editor(page).getByRole('button', { name: 'Save name' }).click();
    await expect(editor(page).getByText(name, { exact: true })).toBeVisible();
  }
  await rename(a.page, 'Moon Bean');
  await a.page.getByRole('button', { name: 'Dog', exact: true }).click();
  await expect(editor(a.page).getByText('Buddy', { exact: true })).toBeVisible();
  await rename(a.page, 'Sunny');
  await a.page.getByRole('button', { name: 'Cat', exact: true }).click();
  await expect(editor(a.page).getByText('Moon Bean', { exact: true })).toBeVisible();
  await a.page.getByRole('button', { name: 'Copy invite link' }).click();
  await expect(a.page.getByText('Invite link copied!')).toBeVisible();
  const invite = await a.page.evaluate(() => navigator.clipboard.readText());
  const room = await a.page.evaluate(() => localStorage.getItem('duodoro:session'));
  if (!room) throw new Error('Missing names test room');
  roomCodes.add(room);
  await b.page.goto('/');
  await b.page.evaluate(({ key, session }) => localStorage.setItem(key, JSON.stringify(session)), { key: AUTH_STORAGE_KEY, session: b.session });
  await b.page.reload();
  await onboard(b.page, 'Names Beta', `nb_${suffix}`);
  await expect(b.page.getByRole('button', { name: 'Focus', exact: true })).toBeVisible();
  await b.page.goto(invite);
  await expect(b.page.getByRole('button', { name: 'Start session', exact: true })).toBeVisible();
  await unlock(b.page);
  await b.page.getByRole('button', { name: 'Rabbit', exact: true }).click();
  await expect(editor(b.page).getByText('Clover', { exact: true })).toBeVisible();
  await rename(b.page, 'W'.repeat(24));
  await expect(a.page.getByText(`Names Beta's companion · ${'W'.repeat(24)}`)).toBeVisible();
  await expect(b.page.getByText("Names Alpha's companion · Moon Bean")).toBeVisible();
  await a.page.reload();
  await expect(editor(a.page).getByText('Moon Bean', { exact: true })).toBeVisible();
  await a.page.setViewportSize({ width: 375, height: 667 });
  await editor(a.page).scrollIntoViewIfNeeded();
  await a.page.screenshot({ path: test.info().outputPath('companion-names-phone.png') });
  await a.page.getByRole('button', { name: 'Flowmodoro', exact: true }).click();
  await a.page.getByRole('button', { name: 'Start session', exact: true }).click();
  await rename(a.page, 'Luna');
  await expect(b.page.getByText("Names Alpha's companion · Luna")).toBeVisible();
  await expect(a.page.getByRole('img', { name: 'Luna, your cat companion' })).toBeVisible();
  await a.page.setViewportSize({ width: 667, height: 375 });
  await editor(a.page).scrollIntoViewIfNeeded();
  const box = await editor(a.page).boundingBox();
  expect(box!.x).toBeGreaterThanOrEqual(0); expect(box!.x + box!.width).toBeLessThanOrEqual(667);
  await a.page.screenshot({ path: test.info().outputPath('companion-names-landscape.png') });
  await a.page.reload();
  await expect(editor(a.page).getByText('Luna', { exact: true })).toBeVisible();
  await editor(a.page).getByRole('button', { name: 'Rename companion' }).click();
  await editor(a.page).getByRole('button', { name: 'Use default name' }).click();
  await expect(editor(a.page).getByText('Mochi', { exact: true })).toBeVisible();
  await expect(b.page.getByText("Names Alpha's companion · Mochi")).toBeVisible();
  await a.page.getByRole('button', { name: 'Leave room' }).click();
  await b.page.getByRole('button', { name: 'Leave room' }).click();
  expect(errors).toEqual([]);
});
