import AxeBuilder from '@axe-core/playwright';
import { randomUUID } from 'node:crypto';
import { test, expect } from './duoFixture';
import { onboard } from './onboard';

test('opt-in shortcuts respect typing, overlays, room eligibility and quiet focus', async ({ duo }) => {
  const { a, roomCodes } = duo;
  await a.page.goto('/');
  await onboard(a.page, 'Shortcut Alpha', `ka_${randomUUID().slice(0, 8)}`);
  await a.page.locator('body').click({ position: { x: 3, y: 3 } });
  await a.page.keyboard.press('t');
  await expect(a.page.getByRole('dialog', { name: 'Stats', exact: true })).toHaveCount(0);
  await a.page.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).click();
  const help = a.page.getByRole('dialog', { name: 'Keyboard shortcuts', exact: true });
  await expect(help.getByRole('checkbox', { name: 'Enable keyboard shortcuts' })).not.toBeChecked();
  await help.getByRole('checkbox').check();
  await a.page.keyboard.press('t');
  await expect(a.page.getByRole('dialog', { name: 'Stats', exact: true })).toHaveCount(0);
  await a.page.keyboard.press('Escape');
  await expect(help).toHaveCount(0);
  await a.page.keyboard.press('t');
  const stats = a.page.getByRole('dialog', { name: 'Stats', exact: true });
  await expect(stats).toBeVisible();
  await a.page.keyboard.press('Escape');
  await expect(stats).toHaveCount(0);
  await a.page.getByRole('button', { name: 'Focus', exact: true }).click();
  const room = await a.page.evaluate(() => localStorage.getItem('duodoro:session'));
  if (!room) throw new Error('Missing shortcut room'); roomCodes.add(room);
  await a.page.getByRole('button', { name: 'Flowmodoro', exact: true }).click();
  const intention = a.page.getByRole('region', { name: 'Session intentions', exact: true });
  await intention.getByRole('button', { name: 'Add intention', exact: true }).click();
  const text = intention.getByRole('textbox', { name: 'Your session intention' });
  await text.fill('Write'); await text.press('s');
  await expect(a.page.getByRole('timer')).toHaveCount(0);
  await text.press('Enter');
  await a.page.getByRole('button', { name: 'Start solo', exact: true }).focus();
  await a.page.keyboard.press('s');
  await expect(a.page.getByRole('timer')).toBeVisible();
  const startTime = await a.page.getByRole('timer').innerText();
  await a.page.keyboard.press('q');
  await expect(a.page.getByRole('checkbox', { name: 'Quiet focus mode' })).toBeChecked();
  await expect(a.page.getByRole('group', { name: 'Pixel reactions' })).toHaveCount(0);
  await a.page.keyboard.press('s');
  await expect(a.page.getByRole('timer')).toBeVisible();
  expect(await a.page.getByRole('timer').innerText()).toMatch(/\d+:\d+/);
  expect(startTime).toMatch(/\d+:\d+/);
  await a.page.keyboard.press('?'); await expect(help).toBeVisible();
  const accessibility = await new AxeBuilder({ page: a.page }).include('[role="dialog"][aria-label="Keyboard shortcuts"]').withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa']).analyze();
  expect(accessibility.violations.map(violation => violation.id)).toEqual([]);
  await a.page.setViewportSize({ width: 375, height: 667 });
  await a.page.screenshot({ path: test.info().outputPath('shortcuts-phone.png') });
  expect(await a.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await a.page.setViewportSize({ width: 667, height: 375 });
  await a.page.screenshot({ path: test.info().outputPath('shortcuts-landscape.png') });
  await help.getByRole('checkbox').uncheck();
  await a.page.keyboard.press('Escape');
  await a.page.keyboard.press('?'); await expect(help).toHaveCount(0);
  await a.page.setViewportSize({ width: 375, height: 667 });
  await a.page.getByRole('button', { name: /^(Open|Toggle) account menu$/ }).click();
  await a.page.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).click();
  await expect(help).toBeVisible();
  await expect(help.getByRole('checkbox')).not.toBeChecked();
  await a.page.keyboard.press('Escape');
  await a.page.getByRole('button', { name: /Leave room/ }).click();
  await expect(a.page.getByRole('button', { name: 'Focus', exact: true })).toBeVisible();
  expect(await a.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await a.page.getByRole('button', { name: /^(Open|Toggle) account menu$/ }).click();
  await a.page.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).click();
  await expect(help).toBeVisible();
});
