import { randomUUID } from 'node:crypto';
import { test, expect, AUTH_STORAGE_KEY } from './duoFixture';
import { onboard } from './onboard';

test('live reactions stay crisp beside moving avatars and do not replay after reconnect', async ({ duo }) => {
  test.setTimeout(120_000);
  const { a, b, roomCodes } = duo;
  const suffix = randomUUID().slice(0, 8);
  const errors: string[] = [];
  for (const actor of [a, b]) actor.page.on('pageerror', () => errors.push('browser error'));
  await a.page.goto('/');
  await onboard(a.page, 'Reaction Alpha', `ra_${suffix}`);
  await a.page.getByRole('button', { name: 'Focus', exact: true }).click();
  await expect(a.page.getByRole('button', { name: 'Start solo', exact: true })).toBeVisible();
  await a.page.getByRole('button', { name: 'Copy invite link' }).click();
  await expect(a.page.getByText('Invite link copied!')).toBeVisible();
  const invite = await a.page.evaluate(() => navigator.clipboard.readText());
  const room = await a.page.evaluate(() => localStorage.getItem('duodoro:session'));
  if (!room) throw new Error('No reaction test room');
  roomCodes.add(room);
  await b.page.goto('/');
  await b.page.evaluate(({ key, session }) => localStorage.setItem(key, JSON.stringify(session)), { key: AUTH_STORAGE_KEY, session: b.session });
  await b.page.reload();
  await onboard(b.page, 'Reaction Beta', `rb_${suffix}`);
  await expect(b.page.getByRole('button', { name: 'Focus', exact: true })).toBeVisible();
  await b.page.goto(invite);
  await expect(a.page.getByRole('button', { name: 'Start session', exact: true })).toBeVisible();
  await a.page.getByRole('button', { name: 'Flowmodoro', exact: true }).click();
  await a.page.getByRole('button', { name: 'Start session', exact: true }).click();
  await a.page.getByRole('button', { name: 'Send heart' }).click();
  for (const actor of [a, b]) await expect(actor.page.getByRole('img', { name: 'Reaction Alpha sent a heart reaction' })).toBeVisible();
  await expect(a.page.getByRole('button', { name: 'Send wave' })).toBeDisabled();
  await a.page.screenshot({ path: test.info().outputPath('reaction-heart-desktop.png') });
  const reaction = a.page.locator('.pixel-reaction-heart');
  expect(await reaction.evaluate(el => getComputedStyle(el).backgroundColor)).not.toBe('rgba(0, 0, 0, 0)');
  for (let i = 0; i < 8; i++) {
    const motion = await reaction.evaluate(el => {
      const m = new DOMMatrix(getComputedStyle(el).transform);
      return [m.a, m.b, m.c, m.d, m.e, m.f];
    });
    expect(motion.slice(0, 4)).toEqual([1, 0, 0, 1]);
    for (const coordinate of motion.slice(4)) expect(Number.isInteger(coordinate)).toBe(true);
    await a.page.waitForTimeout(150);
  }
  await expect(reaction).toHaveCount(0);
  await expect(a.page.getByRole('button', { name: 'Send wave' })).toBeEnabled();
  await a.page.setViewportSize({ width: 375, height: 667 });
  await b.page.getByRole('button', { name: 'Send wave' }).click();
  const wave = a.page.getByRole('img', { name: 'Reaction Beta sent a wave reaction' });
  await expect(wave).toBeVisible();
  await expect(wave.locator('svg')).toHaveAttribute('width', '16');
  await a.page.screenshot({ path: test.info().outputPath('reaction-wave-phone.png') });
  await a.page.reload();
  await expect(a.page.getByRole('button', { name: 'Take break', exact: true })).toBeVisible();
  await expect(wave).toHaveCount(0);
  await a.page.emulateMedia({ reducedMotion: 'reduce' });
  await a.page.getByRole('button', { name: 'Send cheer' }).click();
  const cheer = a.page.locator('.pixel-reaction-cheer');
  await expect(cheer).toBeVisible();
  expect(await cheer.evaluate(el => getComputedStyle(el).animationName)).toBe('none');
  expect(await cheer.evaluate(el => getComputedStyle(el).transform)).toBe('none');
  await a.page.screenshot({ path: test.info().outputPath('reaction-cheer-reduced-motion.png') });
  await expect(cheer).toHaveCount(0);
  await a.page.getByRole('button', { name: 'Take break', exact: true }).click();
  await expect.poll(() => a.page.title()).toContain(' · Break · ');
  await a.page.setViewportSize({ width: 667, height: 375 });
  await expect(a.page.getByRole('button', { name: 'Send wave' })).toBeEnabled();
  await a.page.getByRole('button', { name: 'Send wave' }).click();
  await expect(a.page.getByRole('img', { name: 'Reaction Alpha sent a wave reaction' })).toBeVisible();
  await a.page.screenshot({ path: test.info().outputPath('reaction-break-landscape.png') });
  await a.page.getByRole('button', { name: 'Leave room' }).click();
  await b.page.getByRole('button', { name: 'Leave room' }).click();
  expect(errors).toEqual([]);
});
