import { randomUUID } from 'node:crypto';
import { test, expect } from './duoFixture';
import { onboard } from './onboard';

test('quiet focus persists without resetting Flow and restores controls on breaks', async ({ duo }) => {
  const { a, roomCodes } = duo;
  await a.page.goto('/');
  await onboard(a.page, 'Quiet Alpha', `qa_${randomUUID().slice(0, 8)}`);
  await a.page.getByRole('button', { name: 'Focus', exact: true }).click();
  await a.page.getByRole('button', { name: 'Flowmodoro', exact: true }).click();
  const room = await a.page.evaluate(() => localStorage.getItem('duodoro:session'));
  if (!room) throw new Error('Missing quiet focus room'); roomCodes.add(room);
  const prompt = a.page.getByRole('region', { name: 'Session intentions', exact: true });
  await prompt.getByRole('button', { name: 'Add intention', exact: true }).click();
  await prompt.getByRole('textbox', { name: 'Your session intention' }).fill('Write the opening paragraph');
  await prompt.getByRole('textbox').press('Enter');
  const quiet = a.page.getByRole('checkbox', { name: 'Quiet focus mode' });
  await quiet.check();
  await expect(a.page.getByRole('group', { name: 'Pixel reactions' })).toBeVisible();
  await a.page.getByRole('button', { name: 'Start solo', exact: true }).click();
  await expect(a.page).toHaveTitle(/00:0[2-9] · Flow · Duodoro/);
  await expect(a.page.getByRole('region', { name: 'Session presets' })).toHaveCount(0);
  await expect(quiet).toHaveCount(1);
  const time = () => a.page.getByRole('timer').innerText();
  const seconds = (text: string) => { const [m, s] = text.match(/\d+:\d+/)![0].split(':').map(Number); return m * 60 + s; };
  const before = seconds(await time());
  await expect(a.page.getByRole('group', { name: 'Pixel reactions' })).toHaveCount(0);
  await expect(a.page.getByRole('button', { name: 'Toggle friends panel' })).toHaveCount(0);
  await expect(a.page.getByLabel('Your focus intention:', { exact: false })).toBeVisible();
  await quiet.uncheck();
  await expect(a.page.getByRole('group', { name: 'Pixel reactions' })).toBeVisible();
  expect(seconds(await time())).toBeGreaterThanOrEqual(before);
  await quiet.check(); await a.page.reload();
  await expect(quiet).toBeChecked(); await expect(a.page.getByRole('timer')).toBeVisible();
  expect(seconds(await time())).toBeGreaterThanOrEqual(before);
  await a.page.setViewportSize({ width: 375, height: 667 });
  await quiet.scrollIntoViewIfNeeded();
  await a.page.screenshot({ path: test.info().outputPath('quiet-focus-phone.png') });
  await a.page.setViewportSize({ width: 667, height: 375 });
  await a.page.getByRole('button', { name: 'Take break', exact: true }).scrollIntoViewIfNeeded();
  await a.page.screenshot({ path: test.info().outputPath('quiet-focus-landscape.png') });
  await a.page.getByRole('button', { name: 'Take break', exact: true }).click();
  await expect(a.page).toHaveTitle(/00:\d\d · Break · Duodoro/);
  await expect(a.page.getByRole('group', { name: 'Pixel reactions' })).toBeVisible();
  await expect(a.page.getByRole('button', { name: 'Toggle friends panel' })).toBeVisible();
  await expect(a.page.getByRole('progressbar', { name: 'Break progress' })).toBeVisible();
  await a.page.getByRole('button', { name: 'Stop timer', exact: true }).click();
  await expect(quiet).toBeChecked();
  await a.page.getByRole('button', { name: 'Start solo', exact: true }).click();
  await expect(a.page.getByRole('group', { name: 'Pixel reactions' })).toHaveCount(0);
  await a.page.getByRole('button', { name: /Leave room/ }).click();
  await expect(a.page.getByRole('button', { name: 'Focus', exact: true })).toBeVisible();
});
