import { randomUUID } from "node:crypto";
import { test, expect } from "./duoFixture";
import { onboard } from "./onboard";

test("timer progress follows real phase time, restores on reload, and fits compact scenes", async ({ duo }) => {
  const { a, roomCodes } = duo;
  const page = a.page;
  const suffix = randomUUID().slice(0, 8);
  const errors: string[] = [];
  page.on("pageerror", () => errors.push("browser error"));
  await page.goto("/");
  await onboard(page, "Progress Hero", `progress_${suffix}`);
  await page.getByRole("button", { name: "Focus", exact: true }).click();
  await expect(page.getByRole("button", { name: "Start solo", exact: true })).toBeVisible();
  const room = await page.evaluate(() => localStorage.getItem("duodoro:session"));
  if (!room) throw new Error("The timer test room was not created.");
  roomCodes.add(room);
  await page.getByRole("slider", { name: "Focus", exact: true }).fill("5");
  await page.getByRole("button", { name: "Start solo", exact: true }).click();
  const focus = page.getByRole("progressbar", { name: "Focus progress", exact: true });
  await expect.poll(async () => Number(await focus.getAttribute("aria-valuenow"))).toBeGreaterThanOrEqual(1);
  const beforeReload = Number(await focus.getAttribute("aria-valuenow"));
  await page.reload();
  await expect(focus).toBeVisible();
  expect(Number(await focus.getAttribute("aria-valuenow"))).toBeGreaterThanOrEqual(beforeReload);
  await page.screenshot({ path: test.info().outputPath("timer-focus-desktop.png") });
  async function checkLayout(name: "Focus progress" | "Break progress") {
    const bar = page.getByRole("progressbar", { name, exact: true });
    const box = await bar.boundingBox();
    const timer = await page.getByRole("timer").boundingBox();
    expect(box!.height).toBeGreaterThanOrEqual(12);
    expect(box!.y).toBeGreaterThan(timer!.y + timer!.height);
    expect(box!.x).toBeGreaterThanOrEqual(0);
    expect(box!.x + box!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
  }
  await page.setViewportSize({ width: 375, height: 667 });
  await checkLayout("Focus progress");
  await page.screenshot({ path: test.info().outputPath("timer-focus-phone.png") });
  await page.getByRole("button", { name: "Stop timer", exact: true }).click();
  await expect(focus).toHaveCount(0);
  await page.getByRole("button", { name: "Flowmodoro", exact: true }).click();
  await page.getByRole("button", { name: "Start solo", exact: true }).click();
  await expect.poll(async () => page.title()).toContain(" · Flow · ");
  await expect(focus).toHaveCount(0);
  await expect.poll(async () => page.title()).not.toContain("0:00");
  await page.getByRole("button", { name: "Take break", exact: true }).click();
  const rest = page.getByRole("progressbar", { name: "Break progress", exact: true });
  await expect(rest).toBeVisible();
  expect(Number(await rest.getAttribute("aria-valuenow"))).toBeLessThan(10);
  await page.emulateMedia({ reducedMotion: "reduce" });
  const duration = await rest.locator("div").evaluate((fill) => getComputedStyle(fill).transitionDuration);
  expect(Number.parseFloat(duration)).toBeLessThanOrEqual(0.00001);
  await checkLayout("Break progress");
  await page.screenshot({ path: test.info().outputPath("timer-break-phone.png") });
  await page.setViewportSize({ width: 667, height: 375 });
  await checkLayout("Break progress");
  await rest.scrollIntoViewIfNeeded();
  await page.screenshot({ path: test.info().outputPath("timer-break-landscape.png") });
  const beforeSync = Number(await rest.getAttribute("aria-valuenow"));
  await page.evaluate(() => document.dispatchEvent(new Event("visibilitychange")));
  await expect.poll(async () => Number(await rest.getAttribute("aria-valuenow"))).toBeGreaterThanOrEqual(beforeSync);
  await page.getByRole("button", { name: "Leave room" }).click();
  expect(errors).toEqual([]);
});
